name: auto_updater_windows
description: Windows implementation of the auto_updater plugin.
version: 0.2.1
repository: https://github.com/leanflutter/auto_updater/tree/main/packages/auto_updater_windows
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  auto_updater_platform_interface:
    path: ../auto_updater_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  plugin:
    implements: auto_updater
    platforms:
      windows:
        pluginClass: AutoUpdaterWindowsPluginCApi
